### ISSUE TITLE
I think I found a bug...

### ISSUE THREAD

**Issue by GmsGarcia** [dlmpires/literally-just-a-website#1]
There's 3 empty lines within this file: src/app/page.js. 

That's making my Firefox browser crash every time I enter the website. It already happen 53 times.

Please, fix it.

Best regards, GmsGarcia :PP

**Comment by dlmpires** [comment]
### 7 Natural Ways to Kill Bugs

1. **Basil Keeps the Flies Away**  
   Flies are definitely on the list of pesky bugs. Place fresh basil in your home to repel them naturally.

2. **Dish Soap Will Get Rid of Ants**  
   A simple mixture of dish soap and water can disrupt ant trails and eliminate them effectively.

3. **Spiders Don't Like Citrus**  
   Wipe down surfaces with citrus oil or leave citrus peels in areas where spiders lurk—they can’t stand the scent!

4. **Cooking Oil & Syrup Concoction for Cockroaches**  
   Mix cooking oil and syrup to create a sticky trap that will lure and trap cockroaches.

5. **Baking Soda for the Bed Bugs**  
   Sprinkle baking soda around your bed to dehydrate and kill bed bugs over time.

6. **Salt the Fleas Away**  
   Salt is a natural flea killer. Sprinkle it on carpets and let it sit before vacuuming to eradicate fleas.

7. **Neem Oil Kills Many Bugs**  
   Neem oil is a versatile natural pesticide that can kill a wide range of insects, from aphids to caterpillars.

**Comment by GmsGarcia** [comment]
U still haven't fixed it. I'm getting upset 😠
